<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ['code' => 'AF','name' => 'Afghanistan','phone' => '93','price_type' => 'High Income'],
            ['code' => 'AX','name' => 'Åland Islands','phone' => '358','price_type' => 'High Income'],
            ['code' => 'AL','name' => 'Albania','phone' => '355','price_type' => 'High Income'],
            ['code' => 'DZ','name' => 'Algeria','phone' => '213','price_type' => 'High Income'],
            ['code' => 'AS','name' => 'American Samoa','phone' => '1','price_type' => 'High Income'],
            ['code' => 'AD','name' => 'Andorra','phone' => '376','price_type' => 'High Income'],
            ['code' => 'AO','name' => 'Angola','phone' => '244','price_type' => 'High Income'],
            ['code' => 'AI','name' => 'Anguilla','phone' => '1','price_type' => 'High Income'],
            ['code' => 'AQ','name' => 'Antarctica','phone' => '672','price_type' => 'High Income'],
            ['code' => 'AG','name' => 'Antigua and Barbuda','phone' => '1','price_type' => 'High Income'],
            ['code' => 'AR','name' => 'Argentina','phone' => '54','price_type' => 'High Income'],
            ['code' => 'AM','name' => 'Armenia','phone' => '374','price_type' => 'High Income'],
            ['code' => 'AW','name' => 'Aruba','phone' => '297','price_type' => 'High Income'],
            ['code' => 'AU','name' => 'Australia','phone' => '61','price_type' => 'High Income'],
            ['code' => 'AT','name' => 'Austria','phone' => '43','price_type' => 'High Income'],
            ['code' => 'AZ','name' => 'Azerbaijan','phone' => '994','price_type' => 'High Income'],
            ['code' => 'BS','name' => 'Bahamas','phone' => '1','price_type' => 'High Income'],
            ['code' => 'BH','name' => 'Bahrain','phone' => '973','price_type' => 'High Income'],
            ['code' => 'BD','name' => 'Bangladesh','phone' => '880','price_type' => 'High Income'],
            ['code' => 'BB','name' => 'Barbados','phone' => '1','price_type' => 'High Income'],
            ['code' => 'BY','name' => 'Belarus','phone' => '375','price_type' => 'High Income'],
            ['code' => 'BE','name' => 'Belgium','phone' => '32','price_type' => 'High Income'],
            ['code' => 'BZ','name' => 'Belize','phone' => '501','price_type' => 'High Income'],
            ['code' => 'BJ','name' => 'Benin','phone' => '229','price_type' => 'High Income'],
            ['code' => 'BM','name' => 'Bermuda','phone' => '1','price_type' => 'High Income'],
            ['code' => 'BT','name' => 'Bhutan','phone' => '975','price_type' => 'High Income'],
            ['code' => 'BO','name' => 'Bolivia (Plurinational State of)','phone' => '591','price_type' => 'High Income'],
            ['code' => 'BA','name' => 'Bosnia and Herzegovina','phone' => '387','price_type' => 'High Income'],
            ['code' => 'BW','name' => 'Botswana','phone' => '267','price_type' => 'High Income'],
            ['code' => 'BV','name' => 'Bouvet Island','phone' => '55','price_type' => 'High Income'],
            ['code' => 'BR','name' => 'Brazil','phone' => '55','price_type' => 'High Income'],
            ['code' => 'IO','name' => 'British Indian Ocean Territory','phone' => '246','price_type' => 'High Income'],
            ['code' => 'BN','name' => 'Brunei Darussalam','phone' => '673','price_type' => 'High Income'],
            ['code' => 'BG','name' => 'Bulgaria','phone' => '359','price_type' => 'High Income'],
            ['code' => 'BF','name' => 'Burkina Faso','phone' => '226','price_type' => 'High Income'],
            ['code' => 'BI','name' => 'Burundi','phone' => '257','price_type' => 'High Income'],
            ['code' => 'CV','name' => 'Cabo Verde','phone' => '238','price_type' => 'High Income'],
            ['code' => 'KH','name' => 'Cambodia','phone' => '855','price_type' => 'High Income'],
            ['code' => 'CM','name' => 'Cameroon','phone' => '237','price_type' => 'High Income'],
            ['code' => 'CA','name' => 'Canada','phone' => '1','price_type' => 'High Income'],
            ['code' => 'BQ','name' => 'Caribbean Netherlands','phone' => '599','price_type' => 'High Income'],
            ['code' => 'KY','name' => 'Cayman Islands','phone' => '1','price_type' => 'High Income'],
            ['code' => 'CF','name' => 'Central African Republic','phone' => '236','price_type' => 'High Income'],
            ['code' => 'TD','name' => 'Chad','phone' => '235','price_type' => 'High Income'],
            ['code' => 'CL','name' => 'Chile','phone' => '56','price_type' => 'High Income'],
            ['code' => 'CN','name' => 'China','phone' => '86','price_type' => 'High Income'],
            ['code' => 'CX','name' => 'Christmas Island','phone' => '61','price_type' => 'High Income'],
            ['code' => 'CC','name' => 'Cocos (Keeling) Islands','phone' => '61','price_type' => 'High Income'],
            ['code' => 'CO','name' => 'Colombia','phone' => '57','price_type' => 'High Income'],
            ['code' => 'KM','name' => 'Comoros','phone' => '269','price_type' => 'High Income'],
            ['code' => 'CG','name' => 'Congo','phone' => '242','price_type' => 'High Income'],
            ['code' => 'CD','name' => 'Congo, Democratic Republic of the','phone' => '243','price_type' => 'High Income'],
            ['code' => 'CK','name' => 'Cook Islands','phone' => '682','price_type' => 'High Income'],
            ['code' => 'CR','name' => 'Costa Rica','phone' => '506','price_type' => 'High Income'],
            ['code' => 'HR','name' => 'Croatia','phone' => '385','price_type' => 'High Income'],
            ['code' => 'CU','name' => 'Cuba','phone' => '53','price_type' => 'High Income'],
            ['code' => 'CW','name' => 'Curaçao','phone' => '599','price_type' => 'High Income'],
            ['code' => 'CY','name' => 'Cyprus','phone' => '357','price_type' => 'High Income'],
            ['code' => 'CZ','name' => 'Czech Republic','phone' => '420','price_type' => 'High Income'],
            ['code' => 'CI','name' => 'Côte d\'Ivoire','phone' => '225','price_type' => 'High Income'],
            ['code' => 'DK','name' => 'Denmark','phone' => '45','price_type' => 'High Income'],
            ['code' => 'DJ','name' => 'Djibouti','phone' => '253','price_type' => 'High Income'],
            ['code' => 'DM','name' => 'Dominica','phone' => '1','price_type' => 'High Income'],
            ['code' => 'DO','name' => 'Dominican Republic','phone' => '1','price_type' => 'High Income'],
            ['code' => 'EC','name' => 'Ecuador','phone' => '593','price_type' => 'High Income'],
            ['code' => 'EG','name' => 'Egypt','phone' => '20','price_type' => 'High Income'],
            ['code' => 'SV','name' => 'El Salvador','phone' => '503','price_type' => 'High Income'],
            ['code' => 'GQ','name' => 'Equatorial Guinea','phone' => '240','price_type' => 'High Income'],
            ['code' => 'ER','name' => 'Eritrea','phone' => '291','price_type' => 'High Income'],
            ['code' => 'EE','name' => 'Estonia','phone' => '372','price_type' => 'High Income'],
            ['code' => 'SZ','name' => 'Eswatini (Swaziland)','phone' => '268','price_type' => 'High Income'],
            ['code' => 'ET','name' => 'Ethiopia','phone' => '251','price_type' => 'High Income'],
            ['code' => 'FK','name' => 'Falkland Islands (Malvinas)','phone' => '500','price_type' => 'High Income'],
            ['code' => 'FO','name' => 'Faroe Islands','phone' => '298','price_type' => 'High Income'],
            ['code' => 'FJ','name' => 'Fiji','phone' => '679','price_type' => 'High Income'],
            ['code' => 'FI','name' => 'Finland','phone' => '358','price_type' => 'High Income'],
            ['code' => 'FR','name' => 'France','phone' => '33','price_type' => 'High Income'],
            ['code' => 'GF','name' => 'French Guiana','phone' => '594','price_type' => 'High Income'],
            ['code' => 'PF','name' => 'French Polynesia','phone' => '689','price_type' => 'High Income'],
            ['code' => 'TF','name' => 'French Southern Territories','phone' => '262','price_type' => 'High Income'],
            ['code' => 'GA','name' => 'Gabon','phone' => '241','price_type' => 'High Income'],
            ['code' => 'GM','name' => 'Gambia','phone' => '220','price_type' => 'High Income'],
            ['code' => 'GE','name' => 'Georgia','phone' => '995','price_type' => 'High Income'],
            ['code' => 'DE','name' => 'Germany','phone' => '49','price_type' => 'High Income'],
            ['code' => 'GH','name' => 'Ghana','phone' => '233','price_type' => 'High Income'],
            ['code' => 'GI','name' => 'Gibraltar','phone' => '350','price_type' => 'High Income'],
            ['code' => 'GR','name' => 'Greece','phone' => '30','price_type' => 'High Income'],
            ['code' => 'GL','name' => 'Greenland','phone' => '299','price_type' => 'High Income'],
            ['code' => 'GD','name' => 'Grenada','phone' => '1','price_type' => 'High Income'],
            ['code' => 'GP','name' => 'Guadeloupe','phone' => '590','price_type' => 'High Income'],
            ['code' => 'GU','name' => 'Guam','phone' => '1','price_type' => 'High Income'],
            ['code' => 'GT','name' => 'Guatemala','phone' => '502','price_type' => 'High Income'],
            ['code' => 'GG','name' => 'Guernsey','phone' => '44','price_type' => 'High Income'],
            ['code' => 'GN','name' => 'Guinea','phone' => '224','price_type' => 'High Income'],
            ['code' => 'GW','name' => 'Guinea-Bissau','phone' => '245','price_type' => 'High Income'],
            ['code' => 'GY','name' => 'Guyana','phone' => '592','price_type' => 'High Income'],
            ['code' => 'HT','name' => 'Haiti','phone' => '509','price_type' => 'High Income'],
            ['code' => 'HM','name' => 'Heard Island and Mcdonald Islands','phone' => '61','price_type' => 'High Income'],
            ['code' => 'HN','name' => 'Honduras','phone' => '504','price_type' => 'High Income'],
            ['code' => 'HK','name' => 'Hong Kong','phone' => '852','price_type' => 'High Income'],
            ['code' => 'HU','name' => 'Hungary','phone' => '36','price_type' => 'High Income'],
            ['code' => 'IS','name' => 'Iceland','phone' => '354','price_type' => 'High Income'],
            ['code' => 'IN','name' => 'India','phone' => '91','price_type' => 'High Income'],
            ['code' => 'ID','name' => 'Indonesia','phone' => '62','price_type' => 'High Income'],
            ['code' => 'IR','name' => 'Iran','phone' => '98','price_type' => 'High Income'],
            ['code' => 'IQ','name' => 'Iraq','phone' => '964','price_type' => 'High Income'],
            ['code' => 'IE','name' => 'Ireland','phone' => '353','price_type' => 'High Income'],
            ['code' => 'IM','name' => 'Isle of Man','phone' => '44','price_type' => 'High Income'],
            ['code' => 'IL','name' => 'Israel','phone' => '972','price_type' => 'High Income'],
            ['code' => 'IT','name' => 'Italy','phone' => '39','price_type' => 'High Income'],
            ['code' => 'JM','name' => 'Jamaica','phone' => '1','price_type' => 'High Income'],
            ['code' => 'JP','name' => 'Japan','phone' => '81','price_type' => 'High Income'],
            ['code' => 'JE','name' => 'Jersey','phone' => '44','price_type' => 'High Income'],
            ['code' => 'JO','name' => 'Jordan','phone' => '962','price_type' => 'High Income'],
            ['code' => 'KZ','name' => 'Kazakhstan','phone' => '7','price_type' => 'High Income'],
            ['code' => 'KE','name' => 'Kenya','phone' => '254','price_type' => 'High Income'],
            ['code' => 'KI','name' => 'Kiribati','phone' => '686','price_type' => 'High Income'],
            ['code' => 'KP','name' => 'Korea, North','phone' => '850','price_type' => 'High Income'],
            ['code' => 'KR','name' => 'Korea, South','phone' => '82','price_type' => 'High Income'],
            ['code' => 'XK','name' => 'Kosovo','phone' => '383','price_type' => 'High Income'],
            ['code' => 'KW','name' => 'Kuwait','phone' => '965','price_type' => 'High Income'],
            ['code' => 'KG','name' => 'Kyrgyzstan','phone' => '996','price_type' => 'High Income'],
            ['code' => 'LA','name' => 'Lao People\'s Democratic Republic','phone' => '856','price_type' => 'High Income'],
            ['code' => 'LV','name' => 'Latvia','phone' => '371','price_type' => 'High Income'],
            ['code' => 'LB','name' => 'Lebanon','phone' => '961','price_type' => 'High Income'],
            ['code' => 'LS','name' => 'Lesotho','phone' => '266','price_type' => 'High Income'],
            ['code' => 'LR','name' => 'Liberia','phone' => '231','price_type' => 'High Income'],
            ['code' => 'LY','name' => 'Libya','phone' => '218','price_type' => 'High Income'],
            ['code' => 'LI','name' => 'Liechtenstein','phone' => '423','price_type' => 'High Income'],
            ['code' => 'LT','name' => 'Lithuania','phone' => '370','price_type' => 'High Income'],
            ['code' => 'LU','name' => 'Luxembourg','phone' => '352','price_type' => 'High Income'],
            ['code' => 'MO','name' => 'Macao','phone' => '853','price_type' => 'High Income'],
            ['code' => 'MK','name' => 'Macedonia North','phone' => '389','price_type' => 'High Income'],
            ['code' => 'MG','name' => 'Madagascar','phone' => '261','price_type' => 'High Income'],
            ['code' => 'MW','name' => 'Malawi','phone' => '265','price_type' => 'High Income'],
            ['code' => 'MY','name' => 'Malaysia','phone' => '60','price_type' => 'High Income'],
            ['code' => 'MV','name' => 'Maldives','phone' => '960','price_type' => 'High Income'],
            ['code' => 'ML','name' => 'Mali','phone' => '223','price_type' => 'High Income'],
            ['code' => 'MT','name' => 'Malta','phone' => '356','price_type' => 'High Income'],
            ['code' => 'MH','name' => 'Marshall Islands','phone' => '692','price_type' => 'High Income'],
            ['code' => 'MQ','name' => 'Martinique','phone' => '596','price_type' => 'High Income'],
            ['code' => 'MR','name' => 'Mauritania','phone' => '222','price_type' => 'High Income'],
            ['code' => 'MU','name' => 'Mauritius','phone' => '230','price_type' => 'High Income'],
            ['code' => 'YT','name' => 'Mayotte','phone' => '262','price_type' => 'High Income'],
            ['code' => 'MX','name' => 'Mexico','phone' => '52','price_type' => 'High Income'],
            ['code' => 'FM','name' => 'Micronesia','phone' => '691','price_type' => 'High Income'],
            ['code' => 'MD','name' => 'Moldova','phone' => '373','price_type' => 'High Income'],
            ['code' => 'MC','name' => 'Monaco','phone' => '377','price_type' => 'High Income'],
            ['code' => 'MN','name' => 'Mongolia','phone' => '976','price_type' => 'High Income'],
            ['code' => 'ME','name' => 'Montenegro','phone' => '382','price_type' => 'High Income'],
            ['code' => 'MS','name' => 'Montserrat','phone' => '1','price_type' => 'High Income'],
            ['code' => 'MA','name' => 'Morocco','phone' => '212','price_type' => 'High Income'],
            ['code' => 'MZ','name' => 'Mozambique','phone' => '258','price_type' => 'High Income'],
            ['code' => 'MM','name' => 'Myanmar (Burma)','phone' => '95','price_type' => 'High Income'],
            ['code' => 'NA','name' => 'Namibia','phone' => '264','price_type' => 'High Income'],
            ['code' => 'NR','name' => 'Nauru','phone' => '674','price_type' => 'High Income'],
            ['code' => 'NP','name' => 'Nepal','phone' => '977','price_type' => 'High Income'],
            ['code' => 'NL','name' => 'Netherlands','phone' => '31','price_type' => 'High Income'],
            ['code' => 'AN','name' => 'Netherlands Antilles','phone' => '599','price_type' => 'High Income'],
            ['code' => 'NC','name' => 'New Caledonia','phone' => '687','price_type' => 'High Income'],
            ['code' => 'NZ','name' => 'New Zealand','phone' => '64','price_type' => 'High Income'],
            ['code' => 'NI','name' => 'Nicaragua','phone' => '505','price_type' => 'High Income'],
            ['code' => 'NE','name' => 'Niger','phone' => '227','price_type' => 'High Income'],
            ['code' => 'NG','name' => 'Nigeria','phone' => '234','price_type' => 'High Income'],
            ['code' => 'NU','name' => 'Niue','phone' => '683','price_type' => 'High Income'],
            ['code' => 'NF','name' => 'Norfolk Island','phone' => '672','price_type' => 'High Income'],
            ['code' => 'MP','name' => 'Northern Mariana Islands','phone' => '1','price_type' => 'High Income'],
            ['code' => 'NO','name' => 'Norway','phone' => '47','price_type' => 'High Income'],
            ['code' => 'OM','name' => 'Oman','phone' => '968','price_type' => 'High Income'],
            ['code' => 'PK','name' => 'Pakistan','phone' => '92','price_type' => 'High Income'],
            ['code' => 'PW','name' => 'Palau','phone' => '680','price_type' => 'High Income'],
            ['code' => 'PS','name' => 'Palestine','phone' => '970','price_type' => 'High Income'],
            ['code' => 'PA','name' => 'Panama','phone' => '507','price_type' => 'High Income'],
            ['code' => 'PG','name' => 'Papua New Guinea','phone' => '675','price_type' => 'High Income'],
            ['code' => 'PY','name' => 'Paraguay','phone' => '595','price_type' => 'High Income'],
            ['code' => 'PE','name' => 'Peru','phone' => '51','price_type' => 'Middle Income'],
            ['code' => 'PH','name' => 'Philippines','phone' => '63','price_type' => 'High Income'],
            ['code' => 'PN','name' => 'Pitcairn Islands','phone' => '64','price_type' => 'High Income'],
            ['code' => 'PL','name' => 'Poland','phone' => '48','price_type' => 'High Income'],
            ['code' => 'PT','name' => 'Portugal','phone' => '351','price_type' => 'High Income'],
            ['code' => 'PR','name' => 'Puerto Rico','phone' => '1','price_type' => 'High Income'],
            ['code' => 'QA','name' => 'Qatar','phone' => '974','price_type' => 'High Income'],
            ['code' => 'RE','name' => 'Reunion','phone' => '262','price_type' => 'High Income'],
            ['code' => 'RO','name' => 'Romania','phone' => '40','price_type' => 'High Income'],
            ['code' => 'RU','name' => 'Russian Federation','phone' => '7','price_type' => 'High Income'],
            ['code' => 'RW','name' => 'Rwanda','phone' => '250','price_type' => 'High Income'],
            ['code' => 'BL','name' => 'Saint Barthelemy','phone' => '590','price_type' => 'High Income'],
            ['code' => 'SH','name' => 'Saint Helena','phone' => '290','price_type' => 'High Income'],
            ['code' => 'KN','name' => 'Saint Kitts and Nevis','phone' => '1','price_type' => 'High Income'],
            ['code' => 'LC','name' => 'Saint Lucia','phone' => '1','price_type' => 'High Income'],
            ['code' => 'MF','name' => 'Saint Martin','phone' => '590','price_type' => 'High Income'],
            ['code' => 'PM','name' => 'Saint Pierre and Miquelon','phone' => '508','price_type' => 'High Income'],
            ['code' => 'VC','name' => 'Saint Vincent and the Grenadines','phone' => '1','price_type' => 'High Income'],
            ['code' => 'WS','name' => 'Samoa','phone' => '685','price_type' => 'High Income'],
            ['code' => 'SM','name' => 'San Marino','phone' => '378','price_type' => 'High Income'],
            ['code' => 'ST','name' => 'Sao Tome and Principe','phone' => '239','price_type' => 'High Income'],
            ['code' => 'SA','name' => 'Saudi Arabia','phone' => '966','price_type' => 'High Income'],
            ['code' => 'SN','name' => 'Senegal','phone' => '221','price_type' => 'High Income'],
            ['code' => 'RS','name' => 'Serbia','phone' => '381','price_type' => 'High Income'],
            ['code' => 'CS','name' => 'Serbia and Montenegro','phone' => '381','price_type' => 'High Income'],
            ['code' => 'SC','name' => 'Seychelles','phone' => '248','price_type' => 'High Income'],
            ['code' => 'SL','name' => 'Sierra Leone','phone' => '232','price_type' => 'High Income'],
            ['code' => 'SG','name' => 'Singapore','phone' => '65','price_type' => 'High Income'],
            ['code' => 'SX','name' => 'Sint Maarten','phone' => '1','price_type' => 'High Income'],
            ['code' => 'SK','name' => 'Slovakia','phone' => '421','price_type' => 'High Income'],
            ['code' => 'SI','name' => 'Slovenia','phone' => '386','price_type' => 'High Income'],
            ['code' => 'SB','name' => 'Solomon Islands','phone' => '677','price_type' => 'High Income'],
            ['code' => 'SO','name' => 'Somalia','phone' => '252','price_type' => 'High Income'],
            ['code' => 'ZA','name' => 'South Africa','phone' => '27','price_type' => 'High Income'],
            ['code' => 'GS','name' => 'South Georgia and the South Sandwich Islands','phone' => '500','price_type' => 'High Income'],
            ['code' => 'SS','name' => 'South Sudan','phone' => '211','price_type' => 'High Income'],
            ['code' => 'ES','name' => 'Spain','phone' => '34','price_type' => 'High Income'],
            ['code' => 'LK','name' => 'Sri Lanka','phone' => '94','price_type' => 'High Income'],
            ['code' => 'SD','name' => 'Sudan','phone' => '249','price_type' => 'High Income'],
            ['code' => 'SR','name' => 'Suriname','phone' => '597','price_type' => 'High Income'],
            ['code' => 'SJ','name' => 'Svalbard and Jan Mayen','phone' => '47','price_type' => 'High Income'],
            ['code' => 'SE','name' => 'Sweden','phone' => '46','price_type' => 'High Income'],
            ['code' => 'CH','name' => 'Switzerland','phone' => '41','price_type' => 'High Income'],
            ['code' => 'SY','name' => 'Syria','phone' => '963','price_type' => 'High Income'],
            ['code' => 'TW','name' => 'Taiwan','phone' => '886','price_type' => 'High Income'],
            ['code' => 'TJ','name' => 'Tajikistan','phone' => '992','price_type' => 'High Income'],
            ['code' => 'TZ','name' => 'Tanzania','phone' => '255','price_type' => 'High Income'],
            ['code' => 'TH','name' => 'Thailand','phone' => '66','price_type' => 'High Income'],
            ['code' => 'TL','name' => 'Timor-Leste','phone' => '670','price_type' => 'High Income'],
            ['code' => 'TG','name' => 'Togo','phone' => '228','price_type' => 'High Income'],
            ['code' => 'TK','name' => 'Tokelau','phone' => '690','price_type' => 'High Income'],
            ['code' => 'TO','name' => 'Tonga','phone' => '676','price_type' => 'High Income'],
            ['code' => 'TT','name' => 'Trinidad and Tobago','phone' => '1','price_type' => 'High Income'],
            ['code' => 'TN','name' => 'Tunisia','phone' => '216','price_type' => 'High Income'],
            ['code' => 'TR','name' => 'Turkey (Türkiye)','phone' => '90','price_type' => 'High Income'],
            ['code' => 'TM','name' => 'Turkmenistan','phone' => '993','price_type' => 'High Income'],
            ['code' => 'TC','name' => 'Turks and Caicos Islands','phone' => '1','price_type' => 'High Income'],
            ['code' => 'TV','name' => 'Tuvalu','phone' => '688','price_type' => 'High Income'],
            ['code' => 'UM','name' => 'U.S. Outlying Islands','phone' => '1','price_type' => 'High Income'],
            ['code' => 'UG','name' => 'Uganda','phone' => '256','price_type' => 'High Income'],
            ['code' => 'UA','name' => 'Ukraine','phone' => '380','price_type' => 'High Income'],
            ['code' => 'AE','name' => 'United Arab Emirates','phone' => '971','price_type' => 'High Income'],
            ['code' => 'GB','name' => 'United Kingdom','phone' => '44','price_type' => 'High Income'],
            ['code' => 'US','name' => 'United States','phone' => '1','price_type' => 'High Income'],
            ['code' => 'UY','name' => 'Uruguay','phone' => '598','price_type' => 'High Income'],
            ['code' => 'UZ','name' => 'Uzbekistan','phone' => '998','price_type' => 'High Income'],
            ['code' => 'VU','name' => 'Vanuatu','phone' => '678','price_type' => 'High Income'],
            ['code' => 'VA','name' => 'Vatican City Holy See','phone' => '39','price_type' => 'High Income'],
            ['code' => 'VE','name' => 'Venezuela','phone' => '58','price_type' => 'High Income'],
            ['code' => 'VN','name' => 'Vietnam','phone' => '84','price_type' => 'High Income'],
            ['code' => 'VG','name' => 'Virgin Islands, British','phone' => '1','price_type' => 'High Income'],
            ['code' => 'VI','name' => 'Virgin Islands, U.S','phone' => '1','price_type' => 'High Income'],
            ['code' => 'WF','name' => 'Wallis and Futuna','phone' => '681','price_type' => 'High Income'],
            ['code' => 'EH','name' => 'Western Sahara','phone' => '212','price_type' => 'High Income'],
            ['code' => 'YE','name' => 'Yemen','phone' => '967','price_type' => 'High Income'],
            ['code' => 'ZM','name' => 'Zambia','phone' => '260','price_type' => 'High Income'],
            ['code' => 'ZW','name' => 'Zimbabwe','phone' => '263','price_type' => 'High Income']
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
