<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

use App\Models\MemberInstitution;

class MemberInstitutionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $institutions = [
            ['name' => 'ABH Partners', 'country' => null],
            ['name' => 'Academy of Health Sciences', 'country' => null],
            ['name' => 'AFREhealth', 'country' => null],
            ['name' => 'Africa Academy for Public Health (AAPH)', 'country' => null],
            ['name' => 'Africa University', 'country' => null],
            ['name' => 'Aga Khan University', 'country' => null],
            ['name' => 'Albert Einstein College of Medicine', 'country' => null],
            ['name' => 'Alliance for Sustainable Development Foundation', 'country' => null],
            ['name' => 'American Academy of Pediatrics', 'country' => null],
            ['name' => 'American Association of Veterinary Medical Colleges (AAVMC)', 'country' => null],
            ['name' => 'American Dental Education Association (ADEA)', 'country' => null],
            ['name' => 'American University of Antigua', 'country' => null],
            ['name' => 'American University of Beirut', 'country' => null],
            ['name' => 'American University of the Caribbean School of Medicine', 'country' => null],
            ['name' => 'Arcadia University', 'country' => null],
            ['name' => 'Arizona State University', 'country' => null],
            ['name' => 'Arnhold Institute for Global Health / Icahn School of Medicine at Mount Sinai', 'country' => null],
            ['name' => 'Association of American Medical Colleges (AAMC)', 'country' => null],
            ['name' => 'Association of Schools and Programs of Public Health (ASPPH)', 'country' => null],
            ['name' => 'Bahir Dar University', 'country' => null],
            ['name' => 'Barcelona Institute for Global Health', 'country' => null],
            ['name' => 'Bay Area Global Health Alliance', 'country' => null],
            ['name' => 'Baylor College of Medicine', 'country' => null],
            ['name' => 'Bezmialem Vakif University', 'country' => null],
            ['name' => 'Boston College', 'country' => null],
            ['name' => 'Boston University', 'country' => null],
            ['name' => 'BRAC University', 'country' => null],
            ['name' => 'Brown University', 'country' => null],
            ['name' => 'California University of Science and Medicine', 'country' => null],
            ['name' => 'Canadian Association for Global Health (CAGH)', 'country' => null],
            ['name' => 'CDC', 'country' => null],
            ['name' => 'Charles Drew University', 'country' => null],
            ['name' => 'Chemonics International', 'country' => null],
            ['name' => 'Child Family Health International (CFHI)', 'country' => null],
            ['name' => 'China Medical Board', 'country' => null],
            ['name' => 'Columbia University', 'country' => null],
            ['name' => 'CORE Group', 'country' => null],
            ['name' => 'Cornell Medical College', 'country' => null],
            ['name' => 'Creighton University', 'country' => null],
            ['name' => 'CSIS Global Health Policy Center', 'country' => null],
            ['name' => 'CUNY Graduate School of Public Health & Health Policy', 'country' => null],
            ['name' => 'Denison University', 'country' => null],
            ['name' => 'Direct Relief', 'country' => null],
            ['name' => 'Duke University', 'country' => null],
            ['name' => 'DY Patil School of Public Health & University', 'country' => null],
            ['name' => 'Emory University', 'country' => null],
            ['name' => 'EUCLID (Euclid University / Pôle Universitaire Euclide)', 'country' => null],
            ['name' => 'George Mason University', 'country' => null],
            ['name' => 'George Washington University', 'country' => null],
            ['name' => 'Georgetown University', 'country' => null],
            ['name' => 'Global Health Council', 'country' => null],
            ['name' => 'Hackensack Meridian School of Medicine', 'country' => null],
            ['name' => 'Harvard University (Harvard Global Health Institute)', 'country' => null],
            ['name' => 'Indiana University', 'country' => null],
            ['name' => 'Instituto Nacional de Salud Publica (INSP)', 'country' => null],
            ['name' => 'International Cancer Expert Corps, INC', 'country' => null],
            ['name' => 'International Cancer Institute', 'country' => null],
            ['name' => 'International Union for Circumpolar Health (IUCH)', 'country' => null],
            ['name' => 'Jhpiego', 'country' => null],
            ['name' => 'Johns Hopkins University', 'country' => null],
            ['name' => 'JW Lee Center for Global Medicine / Seoul National University', 'country' => null],
            ['name' => 'Kaiser Permanente Bernard J. Tyson School of Medicine', 'country' => null],
            ['name' => 'Karolinska Institutet', 'country' => null],
            ['name' => 'Kathmandu University School of Medical Science', 'country' => null],
            ['name' => 'Kilimanjaro Christian Medical University College', 'country' => null],
            ['name' => 'Lecturio GmbH', 'country' => null],
            ['name' => 'Loma Linda University', 'country' => null],
            ['name' => 'London School of Hygiene & Tropical Medicine', 'country' => null],
            ['name' => 'Loyola University', 'country' => null],
            ['name' => 'Makerere University', 'country' => null],
            ['name' => 'Manila Central University', 'country' => null],
            ['name' => 'Mayo Clinic College of Medicine', 'country' => null],
            ['name' => 'McGill University', 'country' => null],
            ['name' => 'Medical College of Wisconsin', 'country' => null],
            ['name' => 'Medical Education Cooperation with Cuba (MEDDIC)', 'country' => null],
            ['name' => 'Medical University of South Carolina (MUSC) Center for Global Health', 'country' => null],
            ['name' => 'Memorial Sloan Kettering Cancer Center (MSKCC)', 'country' => null],
            ['name' => 'Michigan State University', 'country' => null],
            ['name' => 'Moi University', 'country' => null],
            ['name' => 'Namibia Institute of Global Health', 'country' => null],
            ['name' => 'New York Institute of Technology Center for Global Health', 'country' => null],
            ['name' => 'New York University School of Global Public Health', 'country' => null],
            ['name' => 'NIH', 'country' => null],
            ['name' => 'North Carolina Global Health Alliance', 'country' => null],
            ['name' => 'Northwell Health', 'country' => null],
            ['name' => 'Northwestern University', 'country' => null],
            ['name' => 'Nuvance Health', 'country' => null],
            ['name' => 'Ohio University', 'country' => null],
            ['name' => 'Our Lady of Fatima University', 'country' => null],
            ['name' => 'PACE University', 'country' => null],
            ['name' => 'Phil Simon Clinic Tanzania Project', 'country' => null],
            ['name' => 'Princeton University', 'country' => null],
            ['name' => 'Purdue University', 'country' => null],
            ['name' => 'Queen\'s University', 'country' => null],
            ['name' => 'Queensland University Haiti', 'country' => null],
            ['name' => 'Research America', 'country' => null],
            ['name' => 'Rice University', 'country' => null],
            ['name' => 'Ross University School of Medicine', 'country' => null],
            ['name' => 'Rush University', 'country' => null],
            ['name' => 'Rutgers - The State University of New Jersey', 'country' => null],
            ['name' => 'San Diego State University', 'country' => null],
            ['name' => 'SIMAD University in Mogadishu', 'country' => null],
            ['name' => 'Southern New Hampshire University', 'country' => null],
            ['name' => 'Spinghar Institute of Higher Education', 'country' => null],
            ['name' => 'St. George\'s University', 'country' => null],
            ['name' => 'St. Luke’s Medical Center College of Medicine', 'country' => null],
            ['name' => 'Stanford University', 'country' => null],
            ['name' => 'Stellenbosch University', 'country' => null],
            ['name' => 'SUNY Downstate College of Medicine', 'country' => null],
            ['name' => 'SUNY Stony Brook', 'country' => null],
            ['name' => 'SUNY Upstate Medical University', 'country' => null],
            ['name' => 'Texas Children\'s Hospital', 'country' => null],
            ['name' => 'Texas Tech University Health Sciences Center', 'country' => null],
            ['name' => 'Thomas Jefferson University', 'country' => null],
            ['name' => 'Touro University', 'country' => null],
            ['name' => 'Tufts University', 'country' => null],
            ['name' => 'Tulane University', 'country' => null],
            ['name' => 'Tumaini Foundation for Global Health and Humanitarianism', 'country' => null],
            ['name' => 'Uniformed Services University of the Health Sciences', 'country' => null],
            ['name' => 'United Nations (UN)', 'country' => null],
            ['name' => 'Universidad Peruana Cayetano Heredia', 'country' => null],
            ['name' => 'Universidad San Francisco de Quito', 'country' => null],
            ['name' => 'University at Buffalo (SUNY at Buffalo)', 'country' => null],
            ['name' => 'University for Development Studies School of Medicine', 'country' => null],
            ['name' => 'University of Alabama, Birmingham', 'country' => null],
            ['name' => 'University of Arizona', 'country' => null],
            ['name' => 'University of Bridgeport', 'country' => null],
            ['name' => 'University of British Columbia', 'country' => null],
            ['name' => 'University of California, Berkeley', 'country' => null],
            ['name' => 'University of California, Davis', 'country' => null],
            ['name' => 'University of California, Irvine', 'country' => null],
            ['name' => 'University of California, Los Angeles', 'country' => null],
            ['name' => 'University of California, San Diego', 'country' => null],
            ['name' => 'University of California, San Francisco', 'country' => null],
            ['name' => 'University of Central Florida', 'country' => null],
            ['name' => 'University of Chicago', 'country' => null],
            ['name' => 'University of Cincinnati College of Medicine', 'country' => null],
            ['name' => 'University of Edinburgh', 'country' => null],
            ['name' => 'University of Georgia (USA)', 'country' => null],
            ['name' => 'University of Georgia Tbilisi (EU)', 'country' => null],
            ['name' => 'University of Global Health Equity', 'country' => null],
            ['name' => 'University of Health Sciences and Pharmacy in St. Louis', 'country' => null],
            ['name' => 'University of Hong Kong', 'country' => null],
            ['name' => 'University of Illinois at Chicago', 'country' => null],
            ['name' => 'University of Iowa', 'country' => null],
            ['name' => 'University of Kansas Medical Center', 'country' => null],
            ['name' => 'University of Kentucky', 'country' => null],
            ['name' => 'University of Manitoba', 'country' => null],
            ['name' => 'University of Maryland, Baltimore', 'country' => null],
            ['name' => 'University of Maryland, College Park', 'country' => null],
            ['name' => 'University of Massachusetts T.H. Chan School of Medicine', 'country' => null],
            ['name' => 'University of Medicine and Health Sciences, UMHS Global Health Inst', 'country' => null],
            ['name' => 'University of Miami', 'country' => null],
            ['name' => 'University of Michigan, Ann Arbor', 'country' => null],
            ['name' => 'University of Minnesota, Academic Health Center, Center for Global Health and Social Responsibility', 'country' => null],
            ['name' => 'University of Nairobi', 'country' => null],
            ['name' => 'University of Nebraska (College of Public Health)', 'country' => null],
            ['name' => 'University of North Carolina, Chapel Hill', 'country' => null],
            ['name' => 'University of Notre Dame', 'country' => null],
            ['name' => 'University of Oregon', 'country' => null],
            ['name' => 'University of Pennsylvania', 'country' => null],
            ['name' => 'University of Pittsburgh', 'country' => null],
            ['name' => 'University of Rochester', 'country' => null],
            ['name' => 'University of South Florida', 'country' => null],
            ['name' => 'University of Southern California', 'country' => null],
            ['name' => 'University of Tennessee Health Science Center', 'country' => null],
            ['name' => 'University of Texas Health Science Center at Houston - UTHealth Houston', 'country' => null],
            ['name' => 'University of Texas Health Science Center, San Antonio', 'country' => null],
            ['name' => 'University of Texas Medical Branch, Galveston', 'country' => null],
            ['name' => 'University of Texas Southwestern Medical Center, Dallas', 'country' => null],
            ['name' => 'University of Utah', 'country' => null],
            ['name' => 'University of Uyo - Nigeria', 'country' => null],
            ['name' => 'University of Vermont College of Medicine', 'country' => null],
            ['name' => 'University of Virginia', 'country' => null],
            ['name' => 'University of Washington', 'country' => null],
            ['name' => 'University of Wisconsin, Madison', 'country' => null],
            ['name' => 'University of Wollongong', 'country' => null],
            ['name' => 'Université de Sherbrooke', 'country' => null],
            ['name' => 'Vanderbilt University', 'country' => null],
            ['name' => 'VetAgro Sup', 'country' => null],
            ['name' => 'Virginia Polytechnic Institute and State University', 'country' => null],
            ['name' => 'Wake Forest University', 'country' => null],
            ['name' => 'Washington University in St. Louis', 'country' => null],
            ['name' => 'Wayne State University', 'country' => null],
            ['name' => 'World Health Organization (WHO)', 'country' => null],
            ['name' => 'World Health Summit (WHS)', 'country' => null],
            ['name' => 'Yale University', 'country' => null],
        ];


        foreach ($institutions as $institution) {
            MemberInstitution::create($institution);
        }
    }
}
